 name: 谢无涯的思念

on:
  schedule:
    - cron: '0 0,4,8,12,14 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: 下载代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 运行脚本
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: python wuyan.py
